### ISSUE TITLE
Unknown plugin "transform-runtime" ...

### ISSUE THREAD

**Issue by iamvitali** [shayneo/vue-fuse#15]
Hi, I've installed `vue-fuse` & did `import VueFuse from 'vue-fuse'`.

Getting this error on `npm run dev`:
```
 error  in ./node_modules/vue-fuse/src/VueFuse.vue

Module build failed: ReferenceError: Unknown plugin "transform-runtime" specified in "C:\\xampp\\htdocs\\portal\\node_mo
dules\\vue-fuse\\.babelrc" at 0, attempted to resolve relative to "C:\\xampp\\htdocs\\portal\\node_modules\\vue-fuse"
    at C:\xampp\htdocs\portal\node_modules\babel-core\lib\transformation\file\options\option-manager.js:180:17
    at Array.map (native)
    at Function.normalisePlugins (C:\xampp\htdocs\portal\node_modules\babel-core\lib\transformation\file\options\option-
manager.js:158:20)
    at OptionManager.mergeOptions (C:\xampp\htdocs\portal\node_modules\babel-core\lib\transformation\file\options\option
-manager.js:234:36)
    at OptionManager.init (C:\xampp\htdocs\portal\node_modules\babel-core\lib\transformation\file\options\option-manager
.js:368:12)
    at File.initOptions (C:\xampp\htdocs\portal\node_modules\babel-core\lib\transformation\file\index.js:212:65)
    at new File (C:\xampp\htdocs\portal\node_modules\babel-core\lib\transformation\file\index.js:135:24)
    at Pipeline.transform (C:\xampp\htdocs\portal\node_modules\babel-core\lib\transformation\pipeline.js:46:16)
    at transpile (C:\xampp\htdocs\portal\node_modules\babel-loader\lib\index.js:49:20)
    at C:\xampp\htdocs\portal\node_modules\babel-loader\lib\fs-cache.js:118:18
    at ReadFileContext.callback (C:\xampp\htdocs\portal\node_modules\babel-loader\lib\fs-cache.js:31:21)
    at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:366:13)

 @ ./node_modules/vue-fuse/src/VueFuse.vue 4:2-215
 @ ./node_modules/vue-fuse/index.js
 @ ./node_modules/babel-loader/lib?{"cacheDirectory":true,"presets":[["env",{"modules":false,"targets":{"browsers":["> 2
%"],"uglify":true}}]]}!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./resources/assets/js/components/pa
ge-layout/leftSidebar.vue
 @ ./resources/assets/js/components/page-layout/leftSidebar.vue
 @ ./resources/assets/js/app.js
 @ multi ./resources/assets/js/app.js ./resources/assets/sass/vendor.scss ./resources/assets/sass/app.scss
```

**Comment by iamvitali** [comment]
On my side temporary fixed it with `npm i babel-plugin-transform-runtime --save-dev` & `npm i babel-preset-stage-2 --save-dev`

**Comment by shayneo** [comment]
Thanks for reporting @iamvitali are you on version 1.2.1 or 1.2.0?

I found a similar issue with v 1.2.0 and fixed in 1.2.1

**Comment by iamvitali** [comment]
`  "_id": "vue-fuse@1.2.1",`

:)

**Comment by shayneo** [comment]
cool, are you importing into `main.js` or directly into a vue component?

**Comment by shayneo** [comment]
@iamvitali i couldn't replicate in a test project, perhaps you could share an example that is exhibiting this issue?

**Comment by daverogers** [comment]
I had the same issue; was importing into my main JS file

**Comment by shayneo** [comment]
Hey @daverogers ! Thanks for reporting. Would you mind posting your main.js file so I can try to replicate?
